name=Arducam_Qwiic_CAM
version=2.0.1
author=Arducam <support@arducam.com>
maintainer=Arducam <support@arducam.com>
sentence=An Arduino library to make use of the Qwiic camera. 
paragraph=An Arduino library for Arducam Qwiic camera modules, supporting image capture, camera control, WiFi preview, and USART host protocol examples.
category=Sensors
url=https://github.com/ArduCAM/Arducam_Qwiic_CAM_Arduino
architectures=*
precompiled=full
dot_a_linkage=false
depends=
includes=Arducam_Qwiic_CAM.h
